### ISSUE TITLE
[ERROR] Installing proxy-checker

### ISSUE THREAD

**Issue by aleff-github** [ricerati/proxy-checker-python#11]
Hi I'm having an error when i try to install your lib with the command
`pip install proxy-checker`

I have the following error
`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

My OS is Ubuntu 20.10

The complete output is the following
````
Collecting proxy-checker
  Using cached proxy_checker-0.6-py3-none-any.whl (4.6 kB)
Collecting pycurl
  Using cached pycurl-7.43.0.6.tar.gz (222 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ig21p57c/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ig21p57c/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zwws3678
         cwd: /tmp/pip-install-ig21p57c/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-ig21p57c/pycurl/setup.py", line 236, in configure_unix
        p = subprocess.Popen((self.curl_config(), '--version'),
      File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ig21p57c/pycurl/setup.py", line 988, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-ig21p57c/pycurl/setup.py", line 649, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-ig21p57c/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-ig21p57c/pycurl/setup.py", line 241, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
````

**Comment by ricerati** [comment]
Try this and let me know if it resolves your issue: [https://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing](https://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing)

**Comment by aleff-github** [comment]
Yes, i solved with your stackoverflow link, thanks
